version: "3"

networks:
  laravel-network:
    driver: bridge
volumes:
  dbdata:
    driver: local

services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9980:80
    volumes:
      - ./:/var/www/html
      - ./Docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./.env:/var/www/html/.env
    networks:
      - laravel-network
    links:
      - db:db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: haselko
      MYSQL_DATABASE: webservice
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    volumes:
      - ../mysql/data:/var/lib/mysql
    networks:
      - laravel-network
    restart: unless-stopped

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9981:80
    links:
      - db:db
    networks:
      - laravel-network
    restart: unless-stopped

